name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true
    - run: |
        gem install awesome_bot
        awesome_bot README.md --allow-redirect